name: "workflow TP4"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Run Frontend
        run: |
          cd TP4-PB-Frontend
          npm install
          npm run dev &
          sleep 10 # Aguarda o Vite estabilizar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: |
          cd TP4-PB-Backend
          mvn clean verify

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: TP4-PB-Backend/target/site/jacoco/