name: "workflow TP4"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Run Frontend
        run: |
          cd TP4-PB-Frontend
          npm install
          npm install -g wait-on
          npm run dev &

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Backend in Background
        run: |
          cd TP4-PB-Backend
          mvn spring-boot:run & 

      - name: Wait for Services
        run: |
          # Espera o Front (5173) e o Back (8080) responderem
          wait-on http://localhost:5173 http://localhost:8080 --timeout 90000

      - name: Run Tests
        run: |
          cd TP4-PB-Backend
          mvn test